name: Deploy SST

on:
  push:
    branches:
      - feature/sst

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        if: github.ref == 'refs/heads/feature/sst'
        run: |
          echo "jalanbro"
